# Generated by Django 5.2.11 on 2026-09-29 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_analyticsevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticsevent',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analyticsevent',
            name='session_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
