-- PostgreSQL 16 DDL exported from this project after Django migrations 0001–0004.
-- Reference for a fresh database; use manage.py migrate to install/update the app.
-- Framework auth/admin/session tables are omitted. Django handles on_delete behavior.
--
-- PostgreSQL database dump
--


-- Dumped from database version 16.15 (Ubuntu 16.15-0ubuntu0.24.04.1)
-- Dumped by pg_dump version 16.15 (Ubuntu 16.15-0ubuntu0.24.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: comments_comments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.comments_comments (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    text text NOT NULL,
    author_id bigint NOT NULL,
    question_id bigint NOT NULL
);


--
-- Name: comments_comments_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.comments_comments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.comments_comments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: questions_analyticsevent; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.questions_analyticsevent (
    id bigint NOT NULL,
    event_name character varying(100) NOT NULL,
    search_query character varying(255),
    created_at timestamp with time zone NOT NULL,
    question_id bigint,
    user_id bigint,
    metadata jsonb,
    session_id character varying(64)
);


--
-- Name: questions_analyticsevent_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.questions_analyticsevent ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.questions_analyticsevent_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: questions_question; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.questions_question (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    title character varying(255) NOT NULL,
    description text,
    slug character varying(50) NOT NULL,
    is_active boolean NOT NULL,
    author_id bigint NOT NULL
);


--
-- Name: questions_question_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.questions_question ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.questions_question_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: questions_question_tag; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.questions_question_tag (
    id bigint NOT NULL,
    question_id bigint NOT NULL,
    tag_id bigint NOT NULL
);


--
-- Name: questions_question_tag_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.questions_question_tag ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.questions_question_tag_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tags_tag; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tags_tag (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    deleted_at timestamp with time zone,
    name character varying(255) NOT NULL,
    slug character varying(50) NOT NULL
);


--
-- Name: tags_tag_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tags_tag ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tags_tag_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_customuser; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users_customuser (
    id bigint NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    deleted_at timestamp with time zone,
    email character varying(254) NOT NULL,
    first_name character varying(50) NOT NULL,
    last_name character varying(50) NOT NULL,
    password character varying(254) NOT NULL,
    is_active boolean NOT NULL,
    is_staff boolean NOT NULL,
    avatar character varying(100),
    preffered_language character varying(10) NOT NULL,
    timezone character varying(50) NOT NULL
);


--
-- Name: users_customuser_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users_customuser ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_customuser_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: comments_comments comments_comments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.comments_comments
    ADD CONSTRAINT comments_comments_pkey PRIMARY KEY (id);


--
-- Name: questions_analyticsevent questions_analyticsevent_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.questions_analyticsevent
    ADD CONSTRAINT questions_analyticsevent_pkey PRIMARY KEY (id);


--
-- Name: questions_question questions_question_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.questions_question
    ADD CONSTRAINT questions_question_pkey PRIMARY KEY (id);


--
-- Name: questions_question questions_question_slug_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.questions_question
    ADD CONSTRAINT questions_question_slug_key UNIQUE (slug);


--
-- Name: questions_question_tag questions_question_tag_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.questions_question_tag
    ADD CONSTRAINT questions_question_tag_pkey PRIMARY KEY (id);


--
-- Name: questions_question_tag questions_question_tag_question_id_tag_id_cb3ed60b_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.questions_question_tag
    ADD CONSTRAINT questions_question_tag_question_id_tag_id_cb3ed60b_uniq UNIQUE (question_id, tag_id);


--
-- Name: tags_tag tags_tag_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tags_tag
    ADD CONSTRAINT tags_tag_pkey PRIMARY KEY (id);


--
-- Name: tags_tag tags_tag_slug_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tags_tag
    ADD CONSTRAINT tags_tag_slug_key UNIQUE (slug);


--
-- Name: users_customuser users_customuser_email_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_customuser
    ADD CONSTRAINT users_customuser_email_key UNIQUE (email);


--
-- Name: users_customuser users_customuser_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users_customuser
    ADD CONSTRAINT users_customuser_pkey PRIMARY KEY (id);


--
-- Name: comments_comments_author_id_e4786cdc; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX comments_comments_author_id_e4786cdc ON public.comments_comments USING btree (author_id);


--
-- Name: comments_comments_question_id_09b075b9; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX comments_comments_question_id_09b075b9 ON public.comments_comments USING btree (question_id);


--
-- Name: questions_analyticsevent_question_id_7528f85f; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX questions_analyticsevent_question_id_7528f85f ON public.questions_analyticsevent USING btree (question_id);


--
-- Name: questions_analyticsevent_user_id_a5d14b66; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX questions_analyticsevent_user_id_a5d14b66 ON public.questions_analyticsevent USING btree (user_id);


--
-- Name: questions_question_author_id_f53392d1; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX questions_question_author_id_f53392d1 ON public.questions_question USING btree (author_id);


--
-- Name: questions_question_slug_d16bba50_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX questions_question_slug_d16bba50_like ON public.questions_question USING btree (slug varchar_pattern_ops);


--
-- Name: questions_question_tag_question_id_4dda0a92; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX questions_question_tag_question_id_4dda0a92 ON public.questions_question_tag USING btree (question_id);


--
-- Name: questions_question_tag_tag_id_438f51e8; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX questions_question_tag_tag_id_438f51e8 ON public.questions_question_tag USING btree (tag_id);


--
-- Name: tags_tag_slug_78c2b8d8_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX tags_tag_slug_78c2b8d8_like ON public.tags_tag USING btree (slug varchar_pattern_ops);


--
-- Name: users_customuser_email_6445acef_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX users_customuser_email_6445acef_like ON public.users_customuser USING btree (email varchar_pattern_ops);


--
-- Name: comments_comments comments_comments_author_id_e4786cdc_fk_users_customuser_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.comments_comments
    ADD CONSTRAINT comments_comments_author_id_e4786cdc_fk_users_customuser_id FOREIGN KEY (author_id) REFERENCES public.users_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: comments_comments comments_comments_question_id_09b075b9_fk_questions_question_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.comments_comments
    ADD CONSTRAINT comments_comments_question_id_09b075b9_fk_questions_question_id FOREIGN KEY (question_id) REFERENCES public.questions_question(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: questions_analyticsevent questions_analyticse_question_id_7528f85f_fk_questions; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.questions_analyticsevent
    ADD CONSTRAINT questions_analyticse_question_id_7528f85f_fk_questions FOREIGN KEY (question_id) REFERENCES public.questions_question(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: questions_analyticsevent questions_analyticse_user_id_a5d14b66_fk_users_cus; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.questions_analyticsevent
    ADD CONSTRAINT questions_analyticse_user_id_a5d14b66_fk_users_cus FOREIGN KEY (user_id) REFERENCES public.users_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: questions_question questions_question_author_id_f53392d1_fk_users_customuser_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.questions_question
    ADD CONSTRAINT questions_question_author_id_f53392d1_fk_users_customuser_id FOREIGN KEY (author_id) REFERENCES public.users_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: questions_question_tag questions_question_t_question_id_4dda0a92_fk_questions; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.questions_question_tag
    ADD CONSTRAINT questions_question_t_question_id_4dda0a92_fk_questions FOREIGN KEY (question_id) REFERENCES public.questions_question(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: questions_question_tag questions_question_tag_tag_id_438f51e8_fk_tags_tag_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.questions_question_tag
    ADD CONSTRAINT questions_question_tag_tag_id_438f51e8_fk_tags_tag_id FOREIGN KEY (tag_id) REFERENCES public.tags_tag(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--


